# Generated by Django 2.0.7 on 2019-05-16 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='contacts/profile_images')),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=1)),
                ('group', models.CharField(blank=True, choices=[('1', 'Family'), ('2', 'Friends'), ('3', 'Collegue'), ('4', 'Neighbours'), ('5', 'Relative')], max_length=1)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
